# Generated by Django 4.2.4 on 2025-02-12 15:10

import django.core.validators
from django.db import migrations, models
import src.media.models.identify_document
import src.media.validators


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadidentifydocumentmedia',
            name='image',
            field=models.ImageField(default='images/identify-document/929b58a1-abaf-4e36-919f-1d80e8eade36.jpeg', upload_to=src.media.models.identify_document.upload_image_identify_document, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), src.media.validators.FileSizeValidator(max_size=5242880, min_size=1), src.media.validators.ImageSizeValidator(max_height=4000, max_width=3000, min_height=300, min_width=300)]),
            preserve_default=False,
        ),
    ]
