# Generated by Django 4.2.4 on 2025-07-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalwallet',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='internalwallet',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='internalwallet',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='serviceinvoice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='serviceinvoice',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='serviceinvoice',
            name='is_deleted',
        ),
    ]
