# Generated by Django 5.1.6 on 2025-09-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_remove_internalwallet_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceinvoice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='serviceinvoice',
            name='technician_description',
        ),
        migrations.RemoveField(
            model_name='serviceinvoice',
            name='warranty_month_length',
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='warranty_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='warranty_period',
            field=models.PositiveIntegerField(blank=True, help_text='Warranty period in days.', null=True),
        ),
    ]
