# Generated by Django 5.1.6 on 2025-09-22 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_customerinvoice_invoicedeductionitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='warranty_period',
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='warranty_duration',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدت زمان گارانتی (عدد)'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='warranty_period_days',
            field=models.PositiveIntegerField(blank=True, help_text='اسنپ\u200cشات مدت زمان گارانتی در روزها (حتی اگر دوره اصلی حذف شود).', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدت زمان گارانتی به روز'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='warranty_time_unit',
            field=models.CharField(blank=True, choices=[('DAY', 'روز'), ('MONTH', 'ماه'), ('YEAR', 'سال')], max_length=10, null=True, verbose_name='واحد زمانی گارانتی'),
        ),
    ]
