# Generated by Django 5.1.6 on 2025-09-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_remove_customerinvoice_warranty_period_and_more'),
        ('parametric', '0003_warrantyperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='warranty_duration',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='warranty_period_days',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='warranty_time_unit',
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='warranty_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametric.warrantyperiod'),
        ),
    ]
