# Generated by Django 5.1.6 on 2025-09-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_remove_customerinvoice_warranty_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceDeductionItem',
        ),
    ]
