# Generated by Django 5.1.6 on 2025-09-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_delete_invoicedeductionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='identify_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
