# Generated by Django 5.1.6 on 2025-10-01 17:14

import src.financial.models.customer_invoice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_invoicedeductionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='pdf_file_path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=src.financial.models.customer_invoice.get_invoice_upload_path),
        ),
    ]
