# Generated by Django 5.1.6 on 2025-10-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_customerinvoice_pdf_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinvoice',
            old_name='pdf_file_path',
            new_name='pdf_output',
        ),
    ]
