# Generated by Django 4.2.4 on 2025-06-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistryrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CHECKING', 'Checking'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=12),
        ),
    ]
