# Generated by Django 4.2.4 on 2025-02-12 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistryrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
