# Generated by Django 4.2.4 on 2025-06-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userregistryrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianstatus',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_HOLIDAY', 'In Holiday')], default='active', max_length=20),
        ),
    ]
