# Generated by Django 4.2.4 on 2024-12-25 14:11

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandNameParametric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('fa_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('fa_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTypeParametric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('fa_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('fa_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimingSettingParametric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_wait_referred_job_to_tech_min', models.PositiveIntegerField(default=30)),
                ('is_notify_after_expired_referred_job_to_tech', models.BooleanField(default=True)),
                ('max_wait_determine_referred_job_by_tech_min', models.PositiveIntegerField(default=15)),
                ('is_notify_after_expired_determine_referred_job_by_tech', models.BooleanField(default=True)),
                ('max_jobs_per_day_by_tech', models.PositiveIntegerField(default=3)),
                ('max_processing_jobs_by_tech_hour', models.PositiveIntegerField(default=72)),
                ('is_notify_after_expired_processing_job_by_tech', models.BooleanField(default=True)),
                ('is_cancel_job_after_expired_processing_by_tech', models.BooleanField(default=False)),
                ('max_wait_determine_follow_up_tag_hour', models.PositiveIntegerField(default=24)),
                ('is_notify_after_expired_determine_follow_up_tag', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Timing Settings',
                'verbose_name_plural': 'Timing Settings',
            },
        ),
    ]
