# Generated by Django 4.2.4 on 2025-06-10 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('customer', '0001_initial'),
        ('parametric', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('REFERRED_TO_SHOP', 'Referred To Shop'), ('INVOICING', 'Invoicing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='WAITING', max_length=20)),
                ('customer_description', models.TextField(blank=True, null=True)),
                ('description_for_technician', models.TextField(blank=True, null=True)),
                ('deadline_accepting_at', models.DateTimeField(blank=True, null=True)),
                ('estimate_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('reason_arrival_delayed', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='geo.address')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='parametric.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='customer.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='parametric.devicetype')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('WAITING', 'Waiting'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('REFERRED_TO_SHOP', 'Referred To Shop'), ('INVOICING', 'Invoicing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('WAITING', 'Waiting'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('REFERRED_TO_SHOP', 'Referred To Shop'), ('INVOICING', 'Invoicing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks or notes about the event.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='service.service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', 'created_at'], name='service_ser_service_6e36f2_idx')],
            },
        ),
    ]
