# Generated by Django 4.2.4 on 2025-02-21 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametric', '0001_initial'),
        ('customer', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Assign'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('referred_to_shop', 'Referred to Shop'), ('invoicing', 'Invoicing'), ('pay_invoice', 'Wait For Pay Invoice'), ('pay_fee', 'Waiting for Pay System Fee'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='waiting', max_length=20)),
                ('customer_description', models.TextField(blank=True, null=True)),
                ('description_for_technician', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.address')),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametric.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='customer.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametric.devicetype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
