# Generated by Django 5.1.6 on 2025-07-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_service_deleted_at_remove_service_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='reason_arrival_delayed',
        ),
    ]
