# Generated by Django 5.1.6 on 2025-09-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_service_reason_arrival_delayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('CUSTOMER_INVOICING', 'Customer Invoicing'), ('CUSTOMER_PAYMENT', 'Customer Payment'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('SYSTEM_FEE_INVOICING', 'System Fee Invoicing'), ('SYSTEM_FEE_PAYMENT', 'System Fee Payment'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicehistory',
            name='new_status',
            field=models.CharField(blank=True, choices=[('WAITING', 'Waiting'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('CUSTOMER_INVOICING', 'Customer Invoicing'), ('CUSTOMER_PAYMENT', 'Customer Payment'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('SYSTEM_FEE_INVOICING', 'System Fee Invoicing'), ('SYSTEM_FEE_PAYMENT', 'System Fee Payment'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicehistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('WAITING', 'Waiting'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('CUSTOMER_INVOICING', 'Customer Invoicing'), ('CUSTOMER_PAYMENT', 'Customer Payment'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('SYSTEM_FEE_INVOICING', 'System Fee Invoicing'), ('SYSTEM_FEE_PAYMENT', 'System Fee Payment'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], max_length=20, null=True),
        ),
    ]
