# Generated by Django 5.1.6 on 2025-09-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_uploadcustomersignaturemedia'),
        ('service', '0004_alter_service_status_alter_servicehistory_new_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='customer_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='media.uploadcustomersignaturemedia'),
        ),
        migrations.AddField(
            model_name='service',
            name='expired_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='other_completed_service_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
