# Generated by Django 5.1.6 on 2025-10-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_customerservicesignature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='other_completed_service_description',
            new_name='other_invoice_deduction_description',
        ),
    ]
