# Generated by Django 4.2.4 on 2025-07-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequepay',
            name='cheque_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
