# Generated by Django 4.2.4 on 2025-07-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_chequepay_cheque_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtocardpay',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cardtocardpay',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='cardtocardpay',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='cashpay',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cashpay',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='cashpay',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='chequepay',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='chequepay',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='chequepay',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='onlinepay',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='onlinepay',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='onlinepay',
            name='is_deleted',
        ),
    ]
