# Generated by Django 5.1.6 on 2025-09-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_cardtocardpay_deleted_at_and_more'),
        ('service', '0005_service_customer_signature_service_expired_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpayment',
            name='card_to_card',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='cheque',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='online',
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='card_to_card_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.cardtocardpay'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='cash_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.cashpay'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='cheque_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.chequepay'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='online_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.onlinepay'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.service'),
        ),
    ]
