# Generated by Django 5.1.6 on 2025-09-12 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_customerpayment_card_to_card_and_more'),
        ('service', '0005_service_customer_signature_service_expired_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='service.service'),
        ),
    ]
