# Generated by Django 5.1.6 on 2025-09-26 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_customeronlinepay_alter_customerpayment_online_pay_and_more'),
        ('service', '0007_alter_service_status_alter_servicehistory_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payment', to='service.service'),
        ),
    ]
