# Generated by Django 5.1.6 on 2025-09-26 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_deleted_at_and_more'),
        ('payment', '0008_alter_customerpayment_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeronlinepay',
            name='internal_wallet',
        ),
        migrations.AddField(
            model_name='customeronlinepay',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_online_pays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeronlinepay',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_online_pays', to='customer.customer'),
        ),
    ]
