# Generated by Django 5.1.6 on 2025-09-26 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azbankgateways', '0005_alter_bank_bank_type_alter_bank_created_at_and_more'),
        ('payment', '0009_remove_customeronlinepay_internal_wallet_and_more'),
        ('service', '0007_alter_service_status_alter_servicehistory_new_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeronlinepay',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customeronlinepay',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='card_to_card_pay',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='cash_pay',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='cheque_pay',
        ),
        migrations.RemoveField(
            model_name='customerpayment',
            name='online_pay',
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='card_to_card_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='cash_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='cheque_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='online_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='online_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_pays', to='azbankgateways.bank'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_online_pays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payment', to='service.service'),
        ),
    ]
