# Generated by Django 5.1.6 on 2025-09-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_remove_customeronlinepay_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashpay',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cashpay',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cashpay',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='chequepay',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chequepay',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='chequepay',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='customeronlinepay',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customeronlinepay',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CardToCardPay',
        ),
        migrations.DeleteModel(
            name='CashPay',
        ),
        migrations.DeleteModel(
            name='ChequePay',
        ),
        migrations.DeleteModel(
            name='CustomerOnlinePay',
        ),
    ]
