# Generated by Django 5.1.6 on 2025-09-26 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_remove_cashpay_created_by_remove_cashpay_customer_and_more'),
        ('service', '0007_alter_service_status_alter_servicehistory_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='service.service'),
        ),
    ]
