# Generated by Django 5.1.6 on 2025-09-26 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azbankgateways', '0005_alter_bank_bank_type_alter_bank_created_at_and_more'),
        ('payment', '0014_technicianpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='online_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments', to='azbankgateways.bank'),
        ),
        migrations.AlterField(
            model_name='technicianpayment',
            name='online_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_payments', to='azbankgateways.bank'),
        ),
    ]
