# Generated by Django 4.2.4 on 2024-12-22 19:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('customer_description', models.TextField(blank=True, null=True)),
                ('description_for_technician', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_assign_queue', 'In Assign Queue'), ('wait_assign_technician', 'wait_assign_technician'), ('in_processing', 'In Processing'), ('canceled', 'Canceled'), ('rejected_by_technician', 'Rejected By Technician'), ('done', 'Done')], default='draft', max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_customer', to='customer.customer')),
            ],
        ),
    ]
