# Generated by Django 4.2.4 on 2024-12-23 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_assign_queue', 'In Assign Queue'), ('wait_assign_by_technician', 'Wait Assign By Technician'), ('in_processing', 'In Processing'), ('canceled', 'Canceled'), ('rejected_by_technician', 'Rejected By Technician'), ('done', 'Done')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='AssignedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('wait_assign_by_technician', 'Wait Assign By Technician'), ('approved_by_technician', 'In Processing'), ('canceled_by_admin', 'Canceled By Admin'), ('changed_technician_by_admin', 'Changed Technician By Admin'), ('rejected_by_technician', 'Rejected By Technician')], default='draft', max_length=30)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_determine_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('determined_by_technician_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason_by_technician', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_job_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_job_technician', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
