# Generated by Django 4.2.4 on 2024-12-23 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_alter_job_status_assignedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedjob',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
