# Generated by Django 4.2.4 on 2024-12-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_assignedjob_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedjob',
            name='status',
            field=models.CharField(choices=[('wait_assign_by_technician', 'Wait Assign By Technician'), ('approved_by_technician', 'In Processing'), ('canceled_by_admin', 'Canceled By Admin'), ('changed_technician_by_admin', 'Changed Technician By Admin'), ('rejected_by_technician', 'Rejected By Technician')], default='wait_assign_by_technician', max_length=30),
        ),
    ]
