# Generated by Django 4.2.4 on 2024-12-24 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0004_alter_assignedjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferredJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('wait_determine_by_technician', 'Wait Determine By Technician'), ('accept_by_technician', 'Accept By Technician'), ('canceled_by_admin', 'Canceled By Admin'), ('changed_technician_by_admin', 'Changed Technician By Admin'), ('rejected_by_technician', 'Rejected By Technician'), ('expired', 'Expired')], default='wait_determine_by_technician', max_length=30)),
                ('referred_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_determine_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('determined_by_technician_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason_by_technician', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_job_referred_by', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_job_technician', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_job_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AssignedJob',
        ),
    ]
