# Generated by Django 4.2.4 on 2024-12-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_referredjob_delete_assignedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referredjob',
            name='status',
            field=models.CharField(choices=[('wait_determine_by_technician', 'Wait Determine By Technician'), ('in_processing', 'In Processing'), ('canceled_by_admin', 'Canceled By Admin'), ('changed_technician_by_admin', 'Changed Technician By Admin'), ('rejected_by_technician', 'Rejected By Technician'), ('expired', 'Expired'), ('done', 'Done')], default='wait_determine_by_technician', max_length=30),
        ),
    ]
