# Generated by Django 4.2.4 on 2024-12-26 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametric', '0001_initial'),
        ('job', '0006_alter_referredjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='brand_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_brand_name', to='parametric.brandnameparametric'),
        ),
        migrations.AlterField(
            model_name='job',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_device_type', to='parametric.devicetypeparametric'),
        ),
    ]
