# Generated by Django 4.2.4 on 2024-12-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_brand_name_alter_job_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_referred_queue', 'In Referred Queue'), ('wait_determine_by_technician', 'Wait determine By Technician'), ('in_processing', 'In Processing'), ('canceled', 'Canceled'), ('rejected_by_technician', 'Rejected By Technician'), ('done', 'Done')], default='draft', max_length=30),
        ),
    ]
