# Generated by Django 5.1.6 on 2025-07-19 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['room_id'], name='chat_chatme_room_id_13b7d3_idx'), models.Index(fields=['user_id'], name='chat_chatme_user_id_3cb7fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_id', models.UUIDField()),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('file_id', models.UUIDField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_system_message', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('replied_from_id', models.UUIDField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['room_id'], name='chat_chatme_room_id_95b551_idx'), models.Index(fields=['user_id'], name='chat_chatme_user_id_7580ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('SERVICE', 'Service'), ('TECHNICIAN_DIRECT', 'Technician Direct'), ('ADMIN_DIRECT', 'Admin Direct')], max_length=30)),
                ('service_id', models.UUIDField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['service_id'], name='chat_chatro_service_e9eea0_idx')],
            },
        ),
    ]
