# Generated by Django 4.2.4 on 2025-06-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_adminpinmessageoftechnician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpinmessageoftechnician',
            name='title',
        ),
    ]
