# Generated by Django 4.2.4 on 2025-07-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_remove_adminpinmessageoftechnician_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpinmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='customerpinmessage',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='customerpinmessage',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='customerpinmessage',
            name='seen_at',
        ),
        migrations.RemoveField(
            model_name='customerpinmessage',
            name='title',
        ),
    ]
