# Generated by Django 4.2.4 on 2025-07-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_remove_customerpinmessage_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpinmessageoftechnician',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='adminpinmessageoftechnician',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='adminpinmessageoftechnician',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customerpinmessage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='customerpinmessage',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='customerpinmessage',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='userdashboardpinmessage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='userdashboardpinmessage',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='userdashboardpinmessage',
            name='is_deleted',
        ),
    ]
