# Generated by Django 5.1.6 on 2025-09-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
