# Generated by Django 4.2.4 on 2025-02-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.DeleteModel(
            name='CustomerContactNumber',
        ),
    ]
