# Generated by Django 5.1.6 on 2025-09-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscription_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
