# Generated by Django 4.2.4 on 2024-12-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomModel',
        ),
    ]
