# Generated by Django 4.2.4 on 2024-12-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='status',
            field=models.CharField(choices=[('not_registered', 'Not Registered'), ('checking', 'Checking Identity'), ('registered', 'Registered'), ('rejected', 'Rejected')], default='not_registered', max_length=20),
        ),
    ]
