# Generated by Django 4.2.4 on 2024-12-09 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_uploadidentifydocumentmedia_options'),
        ('user', '0002_alter_baseuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identify_document_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identify_document_medias', to='upload.uploadidentifydocumentmedia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_identify_document_photos',
            field=models.ManyToManyField(blank=True, related_name='other_identify_document_medias', to='upload.uploadidentifydocumentmedia'),
        ),
    ]
