# Generated by Django 4.2.4 on 2024-12-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_identify_document_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='request_register_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
