# Generated by Django 4.2.4 on 2024-12-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_baseuser_request_register_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'User '},
        ),
        migrations.AddField(
            model_name='baseuser',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
