# Generated by Django 4.2.4 on 2024-12-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_baseuser_options_baseuser_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='request_register_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
