# Generated by Django 4.2.4 on 2024-12-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_baseuser_request_register_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
