# Generated by Django 4.2.4 on 2024-12-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlinenumber',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='landlinenumber',
            unique_together={('user', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='mobilenumber',
            unique_together={('user', 'number')},
        ),
    ]
