# Generated by Django 4.2.4 on 2024-12-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_landlinenumber_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'permissions': [('change_another', 'Can change another user')], 'verbose_name': 'User '},
        ),
    ]
