# Generated by Django 4.2.4 on 2024-12-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_baseuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_in_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
