# Generated by Django 4.2.4 on 2024-12-26 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parametric', '0001_initial'),
        ('user', '0010_profile_is_in_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_names', models.ManyToManyField(blank=True, related_name='technician_skill_brand_name', to='parametric.brandnameparametric')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_skill_device_type', to='parametric.devicetypeparametric')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_skill_technician', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
