# Generated by Django 4.2.4 on 2024-12-08 05:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import fixplus.upload.models
import fixplus.upload.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadIdentifyDocumentMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=fixplus.upload.models.upload_image_identify_document, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), fixplus.upload.validators.FileSizeValidator(max_size=5242880, min_size=1), fixplus.upload.validators.ImageSizeValidator(max_height=4000, max_width=3000, min_height=300, min_width=300)])),
            ],
            options={
                'verbose_name': 'Identify Document Medias',
                'verbose_name_plural': 'Identify Document Avatar Medias',
            },
        ),
    ]
