# Generated by Django 4.2.4 on 2024-12-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadidentifydocumentmedia',
            options={'verbose_name': 'Identify Document Medias', 'verbose_name_plural': 'Identify Document Medias'},
        ),
    ]
