# Generated by Django 4.2.4 on 2025-02-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametric', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='fa_description',
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='fa_description',
        ),
    ]
