# Generated by Django 4.2.4 on 2025-02-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric', '0003_brand_deleted_at_brand_deleted_by_brand_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='brand',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
