# Generated by Django 5.1.6 on 2025-09-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric', '0003_warrantyperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='footer_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/footers/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/headers/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/logos/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='phone_numbers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='repair_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='right_text1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='right_text2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/stamps/'),
        ),
    ]
